#!/bin/sh
# pre-commit hook
BOOTUP=color
SETCOLOR_SUCCESS="echo \\033[1;32m"
SETCOLOR_FAILURE="echo \\033[1;31m"
SETCOLOR_NORMAL="echo \\033[0;39m"

function run_check {
  cmd_output=$($@)
  local status=$?
  if [ $status -ne 0 ]; then
    [ "$BOOTUP" = "color" ] && $SETCOLOR_FAILURE
    echo "error with $1" >&2 ":"
    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
    echo $cmd_output
  else
    [ "$BOOTUP" = "color" ] && $SETCOLOR_SUCCESS
    echo "Successful run!"
    [ "$BOOTUP" = "color" ] && $SETCOLOR_NORMAL
  fi
    return $status
}

function ktlint() {
  # Refer: https://github.com/pinterest/ktlint/blob/master/ktlint/src/main/resources/ktlint-git-pre-commit-hook-android.sh
  # Disabled Rules: Import Ordering - since Android Studio's autoformatting utility cannot sort this.
  git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs ktlint --android --relative --disabled_rules=import-ordering .
}

function detekt() {
  git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs echo | tr ' ' ',' | tr ' ' ',' | xargs /usr/local/bin/detekt-cli-1.17.0/bin/detekt-cli --config tooling/.detekt/detekt-config.yml --input
}

echo
echo "Running ktlint on diff..."
run_check ktlint
echo
echo "Running detekt on diff..."
run_check detekt